# debug = true

# https://archive.raspberrypi.org/debian/dists/
# https://github.com/tonistiigi/binfmt
# https://hub.docker.com/_/debian

platforms_skip = [
    "linux/arm/v5",
    "linux/arm/v6",
    "linux/loong64",
    "linux/mips64",
    "linux/mips64le",
    "linux/ppc64le",
    "linux/riscv64",
    "linux/s390x",
]

platforms_allow = [
    "linux/386",
    "linux/amd64",
    "linux/amd64/v2",
    "linux/arm/v7",
    "linux/arm64",
]
