# debug = true
#
# Grow the intersection of target Docker platforms as large as practically possible,
# without generating too much churn.
#
# Tweak this list as platforms emerge (or bitrot).
#
# https://hub.docker.com/_/debian
# https://archive.raspberrypi.org/debian/dists/
# https://github.com/tonistiigi/binfmt
#
platforms_allow = [
    "linux/386",
    "linux/amd64",
    "linux/arm64",
    "linux/armv5",
    "linux/armv7",
]
