# debug = true

# https://archive.raspberrypi.org/debian/dists/
# https://github.com/tonistiigi/binfmt
# https://hub.docker.com/_/debian

platforms = [
    "linux/386",
    "linux/amd64",
    "linux/amd64/v2",
    "linux/arm/v7",
    "linux/arm64",
]

# load_platform = "linux/arm64"
